# Generated by Django 4.0.2 on 2022-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='SwiperImageContent',
        ),
    ]
