# Generated by Django 4.0.2 on 2022-02-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_swipercontent_delete_swiperimagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipercontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='swipercontent',
            name='title',
        ),
    ]
