# Generated by Django 4.0.2 on 2022-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_remove_swipercontent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipercontent',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
